//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agencia()
        {
            this.Rango = new HashSet<Rango>();
            this.User = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Domicilio { get; set; }
        public Nullable<int> LocalidadId { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<int> ZonasId { get; set; }
        public Nullable<decimal> Comision { get; set; }
        public Nullable<decimal> ComisionEncomiendas { get; set; }
        public string Impresora { get; set; }
        public int Reserva { get; set; }
        public Nullable<int> ConTarjeta { get; set; }
        public Nullable<decimal> ComisionTarjeta { get; set; }
        public Nullable<int> DescJubilado { get; set; }
        public Nullable<int> DescEstudiante { get; set; }
        public Nullable<int> DescEspecial { get; set; }
        public Nullable<int> DescMDQ { get; set; }
        public Nullable<int> ComisionPagoDestino { get; set; }
        public Nullable<int> ComisionRecepciona { get; set; }
        public Nullable<int> AvisoBoletos { get; set; }
        public Nullable<int> ComisionValidaCall { get; set; }
        public string Horario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rango> Rango { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}
