//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationTree
    {
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public byte Child { get; set; }
        public int Order { get; set; }
        public int Level { get; set; }
    }
}
