//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesEnco
    {
        public int id { get; set; }
        public string Razon { get; set; }
        public string DNICUIT { get; set; }
        public string Domicilio { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> LocalidadId { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Alta { get; set; }
    }
}
