//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Rel_Reserva_Asiento = new HashSet<Rel_Reserva_Asiento>();
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int Id { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> TipoDocumentoId { get; set; }
        public Nullable<int> Documento { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Domicilio { get; set; }
        public Nullable<int> LocalidadId { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Alta { get; set; }
        public Nullable<int> SexoId { get; set; }
        public string passwd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rel_Reserva_Asiento> Rel_Reserva_Asiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
