//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computadoras
    {
        public int idComputadora { get; set; }
        public string Habilitada { get; set; }
        public string Descripcion { get; set; }
        public string IdUsuario { get; set; }
        public string NombrePC { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaUltimoIngreso { get; set; }
        public string Placa { get; set; }
        public string IpLocal { get; set; }
        public string IpPublica { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string DHCPServer { get; set; }
        public string DHCPEnabled { get; set; }
        public string IPFilterSecurityEnabled { get; set; }
        public string HTTP_USER_AGENT { get; set; }
        public string Explorador { get; set; }
        public string ExploradorVersion { get; set; }
        public string SistemaOperativo { get; set; }
        public string Resolucion { get; set; }
    }
}
