//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentasBancarias
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Banco { get; set; }
        public string Cuenta { get; set; }
        public string Titular { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public Nullable<int> Desactivado { get; set; }
    }
}
