//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorJava
    {
        public int IdError { get; set; }
        public string Descripcion { get; set; }
        public string Error { get; set; }
        public string Codigo { get; set; }
        public string PaginaWeb { get; set; }
        public string Funcion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
