//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estructura
    {
        public int VehiculoId { get; set; }
        public byte Fila { get; set; }
        public byte Columna { get; set; }
        public int TipoId { get; set; }
        public Nullable<int> AsientoId { get; set; }
        public byte Piso { get; set; }
    
        public virtual Asiento Asiento { get; set; }
        public virtual Tipo Tipo { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
