//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastosDetalle
    {
        public int id { get; set; }
        public Nullable<int> idTipoGasto { get; set; }
        public Nullable<int> idAgencia { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Detalle { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> LiquidacionId { get; set; }
        public string idUser { get; set; }
    }
}
