//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class HojaDeRutaMD
    {
        public int id { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string UserId { get; set; }
        public string Coche { get; set; }
        public string Chofer { get; set; }
        public Nullable<int> BolsaId { get; set; }
        public Nullable<decimal> Tarifa { get; set; }
        public Nullable<int> ParadaDestinoId { get; set; }
    }
}
