//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListadoComputadorasPorUsuario
    {
        public string Usuario { get; set; }
        public int idComputadora { get; set; }
        public string Habilitada { get; set; }
        public string DescripcionPC { get; set; }
        public string NombrePC { get; set; }
        public string UltimoUsuarioPC { get; set; }
        public string IpPublica { get; set; }
        public string Explorador { get; set; }
        public string ExploradorVersion { get; set; }
        public string SistemaOperativo { get; set; }
        public string Resolucion { get; set; }
    }
}
