//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogImpVent
    {
        public int id { get; set; }
        public string Userid { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> VentaId { get; set; }
        public Nullable<int> Impreso { get; set; }
    }
}
