//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs2
    {
        public int idlog { get; set; }
        public string iduser { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string menu { get; set; }
        public string sqlcmd { get; set; }
    }
}
