//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class LowCost
    {
        public int idLow { get; set; }
        public Nullable<int> RecorridoId { get; set; }
        public Nullable<int> Dias { get; set; }
        public Nullable<int> Descuento { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
