//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocupacion
    {
        public int ServicioEfectivoId { get; set; }
        public int AsientoId { get; set; }
        public string Distribucion { get; set; }
        public int id { get; set; }
    
        public virtual Asiento Asiento { get; set; }
        public virtual ServicioEfectivo ServicioEfectivo { get; set; }
    }
}
