//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCS
    {
        public int ID { get; set; }
        public string MAC { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> Alta { get; set; }
        public Nullable<bool> Desactivar { get; set; }
        public Nullable<long> Logueos { get; set; }
        public string NombrePC { get; set; }
        public Nullable<System.DateTime> UltimaEntrada { get; set; }
        public Nullable<System.DateTime> UltimaVenta { get; set; }
    }
}
