//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RangoFacturas
    {
        public int Id { get; set; }
        public int AgenciaId { get; set; }
        public double Inicial { get; set; }
        public double Final { get; set; }
        public double Proximo { get; set; }
        public string Activo { get; set; }
    }
}
