//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RangosHuecos
    {
        public int id { get; set; }
        public Nullable<int> Inicial { get; set; }
        public Nullable<int> Final { get; set; }
        public Nullable<int> Disponibles { get; set; }
    }
}
