//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reserva()
        {
            this.Rel_Reserva_Asiento = new HashSet<Rel_Reserva_Asiento>();
        }
    
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int ParadaOrigenId { get; set; }
        public int ParadaDestinoId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> EmpleadoId { get; set; }
        public int AgenciaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rel_Reserva_Asiento> Rel_Reserva_Asiento { get; set; }
    }
}
