//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicioEfectivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServicioEfectivo()
        {
            this.Desdoblamiento = new HashSet<Desdoblamiento>();
            this.Desdoblamiento1 = new HashSet<Desdoblamiento>();
            this.Ocupacion = new HashSet<Ocupacion>();
            this.Rel_Reserva_Asiento = new HashSet<Rel_Reserva_Asiento>();
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ServicioId { get; set; }
        public int VehiculoId { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> ChoferId { get; set; }
        public Nullable<int> ChoferId2 { get; set; }
        public int RecorridoId { get; set; }
        public string Observaciones { get; set; }
        public string Hora { get; set; }
        public int LineaId { get; set; }
        public Nullable<int> Grilla { get; set; }
        public Nullable<int> Excesos { get; set; }
        public Nullable<int> ChoferId3 { get; set; }
        public Nullable<int> ChoferId4 { get; set; }
        public Nullable<int> Disca { get; set; }
        public Nullable<int> Descuento { get; set; }
        public Nullable<int> Cortado { get; set; }
        public Nullable<int> ConGPS { get; set; }
        public string HoraDisca { get; set; }
        public Nullable<int> DescuentoJubilado { get; set; }
        public Nullable<int> DescuentoEstudiante { get; set; }
        public Nullable<int> DescuentoEspecial { get; set; }
        public Nullable<int> LowCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Desdoblamiento> Desdoblamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Desdoblamiento> Desdoblamiento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocupacion> Ocupacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rel_Reserva_Asiento> Rel_Reserva_Asiento { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
