//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Hora { get; set; }
        public string Observaciones { get; set; }
        public int RecorridoId { get; set; }
        public int VehiculoId { get; set; }
        public string Activo { get; set; }
        public byte Dia { get; set; }
        public int LineaId { get; set; }
    
        public virtual Linea Linea { get; set; }
        public virtual Recorrido Recorrido { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
