//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sesiones
    {
        public int idSesion { get; set; }
        public string idUsuario { get; set; }
        public int idComputadora { get; set; }
        public System.DateTime Inicio { get; set; }
        public Nullable<System.DateTime> Fin { get; set; }
        public string Observacion { get; set; }
        public string IpPublica { get; set; }
        public string Password { get; set; }
        public string HTTP_USER_AGENT { get; set; }
        public int Validacion { get; set; }
    }
}
