//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sessions
    {
        public int idSessions { get; set; }
        public string EventType { get; set; }
        public string URL { get; set; }
        public string Referer { get; set; }
        public string RemoteHost { get; set; }
        public string UserAgent { get; set; }
        public string UALanguage { get; set; }
        public string UserID { get; set; }
        public string HostIP { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<System.DateTime> te { get; set; }
    }
}
