//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tapadas
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int ParadaOrigenId { get; set; }
        public int ParadaDestinoId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> AgenciaId { get; set; }
    }
}
