//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarjetasMovimientos
    {
        public int id { get; set; }
        public string NumeroTarjeta { get; set; }
        public string NombreTarjeta { get; set; }
        public Nullable<int> idTarjetas { get; set; }
        public Nullable<int> idVenta { get; set; }
        public string Cupon { get; set; }
        public Nullable<decimal> Monto { get; set; }
    }
}
