//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketLib
    {
        public int Id { get; set; }
        public int Numero { get; set; }
        public Nullable<int> AsientoId { get; set; }
        public Nullable<int> ParadaDestinoId { get; set; }
        public Nullable<int> ParadaOrigenId { get; set; }
        public Nullable<int> ServicioEfectivoId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public string Hora { get; set; }
        public string Observaciones { get; set; }
        public string UserMarca { get; set; }
        public Nullable<System.DateTime> FechaMarca { get; set; }
        public Nullable<int> AgenciaLib { get; set; }
        public Nullable<System.DateTime> Confirmado { get; set; }
    }
}
