//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.Desdoblamiento = new HashSet<Desdoblamiento>();
        }
    
        public int Id { get; set; }
        public int Numero { get; set; }
        public Nullable<int> AsientoId { get; set; }
        public Nullable<int> ParadaDestinoId { get; set; }
        public Nullable<int> ParadaOrigenId { get; set; }
        public Nullable<int> ServicioEfectivoId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Anulado { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> LineaId { get; set; }
        public int VentaId { get; set; }
        public string Hora { get; set; }
        public decimal Tarifa { get; set; }
        public string Observaciones { get; set; }
        public string Cobrado { get; set; }
        public Nullable<decimal> Neto { get; set; }
        public Nullable<int> LiquidacionId { get; set; }
        public Nullable<decimal> ConTarjeta { get; set; }
        public Nullable<int> Remitido { get; set; }
        public Nullable<int> Exceso { get; set; }
        public string UserMarca { get; set; }
        public Nullable<System.DateTime> FechaMarca { get; set; }
        public Nullable<int> Canjeado { get; set; }
        public Nullable<int> CallCenter { get; set; }
        public Nullable<int> ValidoCall { get; set; }
        public Nullable<int> AgenciaValido { get; set; }
        public Nullable<int> Transf { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Desdoblamiento> Desdoblamiento { get; set; }
        public virtual Linea Linea { get; set; }
        public virtual Parada Parada { get; set; }
        public virtual Parada Parada1 { get; set; }
        public virtual ServicioEfectivo ServicioEfectivo { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
