//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Empleado = new HashSet<Empleado>();
            this.Group = new HashSet<Group>();
        }
    
        public string Id { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Descuento { get; set; }
        public string Bonificacion { get; set; }
        public string PrecioAbsoluto { get; set; }
        public string Revendedor { get; set; }
        public int AgenciaId { get; set; }
        public int ParadaDesdeId { get; set; }
        public int ParadaHastaId { get; set; }
        public string Preview { get; set; }
        public Nullable<int> ZonaId { get; set; }
        public Nullable<int> DescJubilado { get; set; }
        public Nullable<int> DescEstudiante { get; set; }
        public Nullable<int> DescEspecial { get; set; }
        public Nullable<int> FCEncomienda { get; set; }
        public Nullable<int> FCEncomiendaSI { get; set; }
        public Nullable<int> DescMDQ { get; set; }
        public Nullable<int> Disca { get; set; }
        public Nullable<int> PagoDestino { get; set; }
        public Nullable<int> Recepcion { get; set; }
        public Nullable<int> ConDescuento { get; set; }
        public Nullable<int> ConRegistro { get; set; }
        public Nullable<int> DescPromo { get; set; }
    
        public virtual Agencia Agencia { get; set; }
        public virtual Parada Parada { get; set; }
        public virtual Parada Parada1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado> Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Group { get; set; }
    }
}
