//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int IdUsuarios { get; set; }
        public Nullable<int> IdIntegrantes { get; set; }
        public Nullable<int> IdComercios { get; set; }
        public string Nombre { get; set; }
        public string Razon { get; set; }
        public string Domicilio { get; set; }
        public string Cp { get; set; }
        public string Localidad { get; set; }
        public string Provincia { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string CUIT { get; set; }
        public string Usuario { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Vence { get; set; }
        public Nullable<System.DateTime> Alta { get; set; }
        public string Nivel { get; set; }
        public Nullable<decimal> DeudaCuotas { get; set; }
        public Nullable<decimal> DeudaOtros { get; set; }
        public string Observ { get; set; }
    }
}
