//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidaComisiones
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string UserId { get; set; }
        public Nullable<int> AgenciaId { get; set; }
        public Nullable<int> TicketId { get; set; }
        public Nullable<int> VentaId { get; set; }
        public Nullable<int> Comi { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> Efectivo { get; set; }
        public Nullable<int> LiquidacionId { get; set; }
        public Nullable<int> AgenciaVtaCallId { get; set; }
        public Nullable<int> LiquidoCall { get; set; }
    }
}
