//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaFacturas
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> EmpleadoId { get; set; }
        public string ClienteId { get; set; }
        public Nullable<byte> Descuento { get; set; }
        public Nullable<byte> Bonificacion { get; set; }
        public Nullable<decimal> PrecioAbsoluto { get; set; }
        public Nullable<int> AgenciaId { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Importe { get; set; }
        public string Abierto { get; set; }
    }
}
