//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> EmpleadoId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<byte> Descuento { get; set; }
        public Nullable<byte> Bonificacion { get; set; }
        public Nullable<decimal> PrecioAbsoluto { get; set; }
        public Nullable<int> AgenciaId { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Importe { get; set; }
        public string Abierto { get; set; }
        public Nullable<decimal> ConTarjeta { get; set; }
        public string TipoDescuento { get; set; }
        public Nullable<int> idPC { get; set; }
        public Nullable<int> CanjeNum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
