//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLiqAConf
    {
        public string Nombre { get; set; }
        public Nullable<decimal> Comision { get; set; }
        public decimal Total { get; set; }
        public Nullable<decimal> Neto { get; set; }
        public Nullable<int> LiquidacionId { get; set; }
        public decimal ConTarjeta { get; set; }
        public Nullable<decimal> ComiT { get; set; }
        public Nullable<decimal> Efectivo { get; set; }
        public Nullable<decimal> ComiTNeto { get; set; }
        public int Id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
