//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class vVentasDesc
    {
        public Nullable<decimal> ESP { get; set; }
        public Nullable<decimal> Estudiante { get; set; }
        public Nullable<decimal> Jubilado { get; set; }
        public Nullable<decimal> MDQ { get; set; }
        public Nullable<decimal> Promo { get; set; }
        public string Nombre { get; set; }
        public System.DateTime Fecha { get; set; }
        public int EmpresaId { get; set; }
    }
}
