//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguilaDoradaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSubenxServicio
    {
        public Nullable<int> ServicioEfectivoId { get; set; }
        public Nullable<int> ParadaOrigenId { get; set; }
        public int Asiento { get; set; }
        public int Seguro { get; set; }
    }
}
